id: P007100
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 12:41:38.839096
source_metadata:
  id: bdr:W1PD88781
  title: བཀའ་ཐང་སྡེ་ལྔ། （ཞོལ་པར་རྙིང་།）
  author: ''
  volumes:
    835d426d508d43c8977c7d5a6e4350cf:
      image_group_id: I1PD88787
      title: Volume 1 of bka' thang sde lnga (zho par rnying)
      volume_number: 1
      total_pages: 710
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
