id: opecha:P007100
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD88781
  title: བཀའ་ཐང་སྡེ་ལྔ། （ཞོལ་པར་རྙིང་།）
  volume:
    835d426d508d43c8977c7d5a6e4350cf:
      image_group_id: I1PD88787
      title: Volume 1 of bka' thang sde lnga (zho par rnying)
      volume_number: 1
      total_pages: 710
  author: ''
ebook_metadata:
  title: བཀའ་ཐང་སྡེ་ལྔ། （ཞོལ་པར་རྙིང་།）
  author: ''
  sku: P007100
  cover: cover.jpg
  layers:
  - pagination
