id: P007100
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD88781
  title: བཀའ་ཐང་སྡེ་ལྔ། （ཞོལ་པར་རྙིང་།）
  author: ''
  volumes:
    aaf866ceb2984171929b66054eb3feec:
      image_group_id: I1PD88787
      title: ''
      volume_number: 1
      total_pages: 710
ebook_metadata:
  title: བཀའ་ཐང་སྡེ་ལྔ། （ཞོལ་པར་རྙིང་།）
  author: ''
  sku: P007100
  cover: cover.jpg
  layers:
  - pagination
